project:
  type: book
  output-dir: docs
  
website: 
  title: "FestinStory"
  navbar:
    left: 
      - href: index.qmd
        text: Home
      - about.qmd
      

book:
  title: "01_Festin Story"
  subtitle: "More than 150 years of family lore"
  author: "By the Family"
  date: "09/dd/2001"
  chapters:
    - index.qmd
    - intro.qmd
    - body.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
  pdf:
    documentclass: scrreprt
    toc: true

editor: visual