# Body

## Our Grand Matriarch

**Mariana Fainsan y Famadico de Festin** was and is "Mama" to all, to both her children and grandchildren. Nobody ever called her "Lola," for she was never old.

She died young at the age of 34, so that most of her children, eleven in all, could not remember, and none of her grandchildren ever saw her.

She died on August 22, 1928, in the days of the American colonial era in the Philippines.

That she lived a long, long time ago could be felt by merely pointing out that she was born on May 24, 1894, when Rizal was still alive and the Spaniards were still our colonizers.

She got married at the very young age of 17 – and stayed married for 17 years – meaning to say that, considering she had eleven children, she delivered a baby roughly every one-and-a-half years.

Of her many children when she passed away, the eldest five were only in their early teens.

Another five were only tots or toddlers. And the youngest, Auntie Pans, was only a none-month-old baby.

All so very many – and so very young – to lose their mother.

When, after World War II and beyond, Mama's children from Uncle Bern the eldest to Auntie Pans the youngest had married and begotten their own children, Mama had long gone.

Understandably, therefore, there was not much talk about Mama in the family – simply because when she was still alive they were too young to have some recollection of her.

Her birth or death anniversary was never commemorated in latter days even once by her grandchildren, through no fault of their own, because she belonged to a distant era that was completely forgotten.

Her eldest ~~child~~ daughter, though – Auntie Nitang – often noted to her children each year the birth and death of her Mama, and prayed for her.

Auntie Nitang in the late 1990s told Sr. Pat she wanted to visit Mama's grave, but unfortunately she was already very sick and dying and Sr. Pat knew it could not be done.

Mama's grandchildren are a rare phenomenon because the numbered, not ten or 20 or 30, but 81 in all, as counted today.

In the past nobody has ever bothered to know the exact count, for her grandchildren were still increasing in number.

A few of them previously did not know exactly where Mama's remains lay buried. Most never even saw her photograph and how she looked like.

Some previously did not know her name – or family name – or that of her beloved mother and father, or where they lived.

They never knew that Mama was a very special person, with quiet and gentle qualities, gracious, pretty, and well-mannered, the only daughter of landed parents in a remote town in a tiny impoverished province many of them had never reached or even heard about.

To many of her descendants, she was practically unknown.

In death she was consigned to oblivion – her life on earth beyond the flashback, but not beyond the veneration today, of grateful present-day Festins.

Yet for a stunning reason – some believe it is a miracle – Mama the unknown will certainly become the best-known and the most enduring among all Festins past, present and future – an irony in which God often indulges with peculiar divine amusement.

But we are going ahead of our story.

Mama could have borne more than her eleven children had she not died at that young age of 34 – at the newly-established Philippine General Hospital.

Some 14 children in all? 16? Or 18? Who knows what might have been?

And she died in such arduous pain, suffering for more than one month, day after cruel day, arising from the harrowing complications of childbirth in an age when medical knowledge in the country had much to be desired - and undesired.

This is not even to mention the birth pains sh had suffered in delivering her previous ten babies.

Today, modern women consider the delivery of one baby as suffering enough. How much more of eleven?

In a real, superior sense, Mama was heroic, selfless, and most important loving – many times over.

The death of old people may not produce so much grief in their relatives because it is expected – so sorry to say this – that they would expire in due time anyway. So their passing is not very unacceptable or saddening.

But the death of Mama was nothing less than devastating.

This was because, first of all, it was unexpected. Second, because she was entitled to many more years of life.

Third, because her visions for her family were still in the making and her dreams were those of the future.

And fourth, because she had so many loved ones from whom she was being torn away.

Besides her husband, Leonardo Festin, whom children and grandchildren alike call "Papa," and her eleven children, she had in her suffering presence during her death her living and loving parents – her mother, Dolores Fainsan, or "Nanay," and per father, Nazario Famadico, or "Tatay."

For them – and most especially for herself – her death was therefore a tragedy of the most bitter kind, an unbearable sorrow.

That she died very much too soon could be gleaned from the fact that Tatay her father outlived her for about 15 years; Nanay her mother outlived her for almost 20 years; and Papa her husband outlived her for a full 42 years.

The normal sequence is that children outlive their parents, and wives outlive their husbands. In the case of Mama, it was the unhappy reverse.

Her death was an agony, physically and emotionally, which we today, who are far in place, in time and in sentiment from that grievous event, will scarcely be able to feel or comprehend in its singular grief.

Sr. Pat says that Auntie Nitang cannot forget visiting Mama in her last few days.

She saw Mama writhing prone with those black, evil-looking "linta" (leeches) placed on her back and getting horribly bloated from sucking her blood – for that was the only way the doctors knew in those stupid days how to cure hypertension, if ever it was a cure at all.

Auntie Nitang heard Mama say, "Aruy, bou-a nindo ina." ("Ooohhh! Take those leeches away!")

Sorrow must have perforated the very depths of the souls of Mama's loved ones. Auntie Nitang told Sr. Pat decades later that in order to cope with the unspeakable grief, Mama's mother Nanay told everybody, "Indi dumdumon," meaning "Don't think about it" – otherwise they would not be able to continue living.

Mama must have known that her time had arrived when she came to the throes of death in that drab PGH room.

She must have consciously felt the last moments when she was being taken back by her Creator, leaving behind and losing everyone whom she loved.

As her vision blurred and her breathing slowed, she must have worried who would take care of her children, especially the younger kids – and her baby, Auntie Pans.

Then maybe in the flash of a visionary moment before death she saw that – with Papa her husband, Tatay her father, Nanay and her children – she had founded a clan that would grow into an extraordinarily big number of direct descendants who ... who would never know her or see her face, or remember her, or hear her voice, or feel her embrace, or experience her love.

What lucky angels those mothers are who see their grandchildren and live with them for years. And Mama's exceptional misfortune must have filled her with indescribable sadness.

We may presume that from heaven decades later, with her earthly agonies overcome and her tears dried up, she saw her grandchildren count among them three priests and three nuns -- Fathers Tony, Jujo and Lorenz, and Sisters Pat, Emma and Cecille – a holy achievement rarely given to mortals.

And today, from above, within three generations, she sees in her grandchildren a host of doctors, nurses, lawyers, engineers, politicians, writers, accountants, farmers, and many others who have lived simple, respectable Christian lives regardless of their circumstance or station – with not a single one of them becoming a problem to the clan, a danger to society, a wretched of the earth, or an apostate to her Christian faith whose prayers and practices she had taught her elder children, who passed them on to her grandchildren.

There are different kinds of matriarchs.

One kind usually refers to old godmothers or great-grandmothers who were stern and willful, who stood against the world within the limited terms of that world, who took a long time and great obsession in their founding and maintenance of a great family.

Mama was none of these things.

She became a grand matriarch posthumously, without deliberate intention, with God using her life as a trigger for so many other lives without her knowing it at that time.

Hers was not a matriarchy of long-term severity and rigor, but one of short-lived tenderness; not a motherhood of old age but of youth; not one that was imposing or dominant but quiet, gentle, inconspicuous, self-effacing – and, most important of all, Christian.

From the little that we know for certain of her character, she did not try to impose her will, her wishes or her wants on her family, especially on her husband.

To her, happiness was cooperation and cooperation was liberation.

It appears that this became the rule of conduct of her three daughters, Auntie Nitang, Nen and Pans, in their family life – because she told them so. Auntie Nitang said this in recalling her Mama.

She was their model.

And that is why Festin parenthood did not produce pestilential children, and Festin marriages have always survived – always, without exception – even in this age of self-indulgence and marital disasters!

According to Auntie Nitang again, Mama totally respected Papa and her parents, especially her great mother, Dolores Fainsan, or Nanay, a matriarch herself of exceptional merit and vision.

From these two matriarchs – along with Francisca Fabon who was the mother of Papa, and other great ancestors like Papa himself – emanated a huge clan, and to them all subsequent Festins owe their existence, and much of their natural attributes, abilities and successes.

Ad so what a great happy vision Mama must have seen in the future Festins – but, alas, they whom she was to love even from the beyond would never see her face.

For God took her away decades before they were born.

In heaven she must have made a plea to the Almighty to preserve her face so her descendants, whom she did not see on earth, could in turn see her, on this same earth, in that same burial ground where Nanay, Tatay, Papa and her children bid her a permanent and final, if tormented, goodbye.

In her most untimely and most unfair death, that may been all that she asked of God.

And 73 years after her death, God granted her earnest, solitary plea, finally fulfilling it in this new century, this new millennium, when she came out of her old grave literally, physically – with her natural eartly face appearing to her descendants like a love letter from paraise, with Jesus as a co-signatory.

The day of revelation came on May 16, 2001.

The golden rays of the afternoon sun, softened by a clouded sky, fell on three simple tombs at the old North Cemetery in Manila – so simple that no one would have suspected they were very special.

They were the final resting place first of Mama, then Papa's on the right side, and on the left Uncle Maning's their eldest child who died in 1940.

On that day, 12 members of the Festin clan had gathered there in respect and reverence – and witnessed a startling phenomenon.

Because flood waters during rainy season regularly reached the area to a certain level, the Festins had decided to exhume the remains of their three loved ones.

Th plan was to cremate the and, through Auntie Purita's arrangements, to put the ashes in urns to be provided by Auntie Nen's daughter Doris, at a place of remembrance and honor – in a crypt in the Shrine of Mount Carmel in Quezon City.

The problem of flooding had worried first of all Uncle Deric and the children of Uncle Bern – Mila, Ike, Cynthia and others.

In the commemoration of Uncle Bert's death the previous year, Festins gathered in their clan compound, which they simply called Indiana, in May (April?) that year, 2001.

They called it Indiana because the street along which it was located was for decades named so. Today, it is named Pilar HIdalgo Lim street.

That month of May (April?), Auntie Pans for some unknown reason was surprisingly the most insistent and vocal in saying that something must be done soon about the cemetery flood problem.

A few days later, on no less than Good Friday, April 13, Auntie Pans, who naturally never saw Mama, being only one month old when she died, passed away quietly, like Uncle Bert, in peace and God's grace.

In fact, unlike other dead bodies seen lying dry and inanimate in funeral parlors, the faces of both Uncle Bert and Auntie Pans looked so peaceful and natural.

Now when Mama's tomb and, later, her coffin, were opened, it was found that her face and head were intact, or incorrupt -- 73 years after burial, as we said!

Her hair – and even her coiffure, done in the style of the old days, that is, parted at the middle and flowing down in slight end curls on both sides of the head and massively to the back – were visible and still orderly!

Except her face and head, her whole body was covered with what appeared to be ribbons and very thick layers of clothing – while traces seemed to show that her legs had already decomposed into bones.

Such must have been the intensity of the sorrow of Papa, Nanay and Tatay and all the rest over her passing that at her burial they really covered her most abundantly with cloth – something that is usually not done by Filipinos to their dead.

The question is: If the other parts of her body decomposed, why not her face and head?

What happened to her body and hands was not known, for they were very thickly covered by cloth, as we said, and no one dared to touch them.

This was because Uncle Deric, her only living child in the Philippines, and Uncle Don, her only living child outside the Philippines and who is in Canada, and was informed by Auntie Manti through Auntie Pat of the phenomenon by telephone, said that her remains should not be touched.

And no one touched her body or the ribbons and sheets of cloth. The cremation plan was for the moment abandoned, even if the Carmel crypt was ready and reserved.

For why should her head and face be preserved by God for that very long period only to be burned today by her descendants?

While there are thousands upon thousands of preserved mummies all over the world, which are ugly and considerably deformed, Mama's case is like that of the incorrupt remains of some Christian saints.

The question is: Why was God's preservation of Mama's face not slovenly or flaed or partial, but perfect – as the photographs show?

Unlike mummies which are damaged at the very least, and appear drawn out by the elements, and are dehydrated, Mama's face incredibly looked as if she was only sleeping, better than those dead faces of people in funeral parlors who had died two or three days earlier.

Her lips were perfectly preserved – and a bit open as if in a smile – while her slightly exposed teeth in unblemished white, without any smudge, and exactly in place!

The 12 Festins were awe-struck. So were some ten cemetery people, most of whom came from nowhere and were watching.

Two of the cemetery workers, who had been contracted to do the exhumation, said they and their fathers for many decades had been exhuming bodies all their lives in that biggest cemetery in the Philippines, and they had never seen anything like it – except another one buried for only 20 years, not far from the Festin burial ground.

Of course, Mama has no monopoly of God's favor, but it appears she has received more of it in the whole Philippines than anyone else.

In other countries around the world, saints like Bernadette of Lourdes and St Clare have remains that stay not just incorrupt, but perfectly incorrupt from head to toe.

In the Philippines, there are ethnic mummies in Ifugao and Bontoc, but they are not perfectly preserved as Mama's face was.

Immediately after her remains were disinterred and her face was seen, no one talked as everybody looked in astonished silence for a few minutes.

After a while some of them made comments as they kept on looking – that her face was not damaged in any way, that there were no scratches, no dust on it, not the slightest dent or discoloration in that light brown countenance which was so peaceful – and so beautiful.

One said her face was like that of a bronze statue – smoothe and impeccable.

The most affected of all was presumably her son Uncle Deric, now 76 years old. He was only three years old when Mama died, and has absolutely no recollection or memory of her in any way.

And now, 73 years after she died, he was fact to face with his Mama again, no longer as a toddler but as an old adult, not in mere photographs but actually in the flesh, and exactly how she looked like when alive!

Apparently, says Berly, no man in all of mankind's history has experienced exactly the same thing as Uncle Deric – and it was said that while looking a Mama his face was indescribable.

Auntie Manti – and the rest who were all Mama's grandchildren – looked at the gently resting face with a feeling which can never perish, or never forget all the years of their lives.

Fr. Lorenz, Mama's dutiful grandson of whom she must be well-pleased, a summa cum laude in his studies in Rome and a good priest by any standard, then led the prayers.

Afterwards a photographer was sought, who nervously arrived – but without a flashbulb.

The photographs he took, nervously again, and depending solely on the slightly subdued sunlight, therefore do not realistically reflect how well-preserved was Mama's face.

A Franciscan nun in the convent of Sr. Emma and Sr. Cecille who was an expert photographer immediately commented upon seeing the photos that the one who took them did not know how to do it.

In fact, the photographs, because of the tree o'clock shadow of the sunrays, present an image that seem to show that her eye sockets were hollow, for dark photographic spots completely covered her peacefully closed eyelids.

But one photograph, though not so good, definitely presents her whole face. with her eyelids closed and perfectly preserved, as if she died only yesterday.

Her wooden casket – yes, it was made of rail wood and not of airtight metal that could have been the scientific reason for the preservation of her face – was slightly damaged but still usable.

After some discussion among the lucky 12 Festins who were there and at first did not know what to do, the on-the-spot decision was made that the remains of Papa and Uncle Maning, all bare bones now in the two tombs beside Mama's be respectfully collected and placed at her feet inside her coffin.

And together the three remains were interred by the awed cemetery workers in the tomb of Papa which, unlike those of Mama and Uncle Maning, happened to be slightly elevated and apparently could not be reached by the seasonal floodwaters.

Part of the phenomenon was that Mama's coffin and her remains, except the head which was slightly raise because of a pillow, contained some water that reached her back and feet, as the cemetery diggers found – and yet the preservation of her face and head was pefect, as the photographs show!

This must be a puzzle for scientists.

For if Mama's face was preserved because of scientific reasons like lack of oxygen in the well-closed coffin, why had her feet and body in the same coffin disintegrated?

How can oxygen or anything gaseous that leads to disintegration of a dead human body be present in one part of the coffin and not in other parts?

Is it not inescapable logic that if one part of the body deteriorated, the rest also should have deteriorated – otherwise it is a miracle, or at least inexplicable scientifically?

St. Margaret Mary's body totally decomposed – except her heart. Other sains aslo had the same uneven preservation, with some organs totally decomposed while others were totally preserved.

Why - and how?

James Curran, an English priest who lived a hundred years ago, seconds before he died, blessed all those present with his right hand. And when his remains were exhumed 20 years later, his whole body had decomposed – except his right hand!

There are other examples of holy people's bodies with such inexplicable partial preservation.

At first Mama's coffin was only slightly pulled out of her tomb, halfway, to allow the viewing of her face for a few minutes.

The cemetery workers, previously instructed to collect all the bones together for cremation, including those of Mama, also did not know what to do at the unexpected sight, and waited for the decision of the family.

Then when the coffin was fully taken out into the open air, the skin of her face suddenly changed in color from perfect bronze brown to qualified reddish strains.

A slight white area, like a shallow scratch, suddenly appeared on her right cheek, as if caused by a waft of wind.

In other words, her face immediately started to deteriorate or decompose – not only from the changed chemical atmosphere, but probably from the fact that the purpose of its preservation, that is, to be seen by her grandchildren, was already fulfilled, so there was no longer any use for further preservation.

As her coffin was being carried to Papa's tomb, it bumped twice on the cement – and her head, as result of the bumping, was jolted and slighly turned to the left, her beautiful face with that aquiline nose now seen from another angle from her right – and the sight was awesome.

It was as if Mama was alive and moving!

Then the coffin, now also containing the bones of Papa and Uncle Maning, was entombed the second time, with the Festins who had now seen her for the first time still not finally decided on what to do with her remains.

Next day Fr. Lorenz wrote Fr. Jujo, who was in Belgium for advanced theological studies. He shared the letter to Sr. Pat, who was also in Belgium as a missionary nun serving poor Eastern European immigrants to that country.

Fr. Lorenz in his letter said:

"It was an unforgettable day for me. Would you believe, for the very first time, I saw the face of our paternal grandmother?

"It all started when our cousins, upon the suggestion of Monique, came up with a plan to have the remains of Papa, Mama and Uncle Maning removed from their tombs and cremated —-

"The idea was to make our grandparents' remains accessible to us so that we can readily visit them.

"We finalized everything last Saturday. Every family contributed P5,000 for expenses."

Fr. Lorenz then dwelt on the exhumation and the description of Mama's remains, saying among many other things:

"Everything in her face had practically been preserved, including her eyelids that were peacefully closed, the nose that resembled those of many of our cousins.

"And the lips partly revealed her teeth. The effect was a subdued smile.

"Her face exhibited a countenance that I can hardly fathom or comprehend ... (It was) tranquil and sublime. Full of joy. Full of peace.

"That her face had been preserved all throughout these decades made me think deeply how much love we must have received from her ...

"And I remembered Auntie Pans.

"She never saw the face of her mother. She was just 33 days old when Mama died. Sadly she herself died 33 days before her mother's mortal and yet ever-youthful face was rediscovered ...."

Berly felt a better thing could be done than just leaving Mama's incorrupt face and head locked inside a tomb.

She argued that it should again be taken out of entombment, deliberately preserved, taken cared of and and venerated in a private place.

But where and how and by whom?

Auntie Manti and her children proceeded to ask funeral parlors and hospitals in Metro Manila for an embalmer or anyone who knows about body preservation, and how to actually do it.

But they were told that Mama, having died 73 years ago, was the only case of its kind that they had heard of.

There were a few in some cemeteries that were exhumed and found still incorrupt after ten or 20 years or so, but not 70 years – and they said they did not have the technical capability to do the preservation.

Besides, bodies, to be preserved – but preserved only for a few weeks at the most – are treated immediately after death, with formalin injected into their blood vessels while still fresh, long before the onset of decomposition.

Nobody, it seemed, knew how to preserve a body by covering it with wax, as done abroad – and as done on the remains of Ferdinand Marcos immediately after he died in Hawaii.

The clan was discouraged by the backbreaking aspects of the problem, especially long-term maintenance.

But Bebet said she was willing to devote herself to caring for Mama's incorrupt face and head if the decision was made to have them indefinitely preserved.

Because of Bebet, the wind changed and the preservation plan was even more enthusiastically discussed.

Berly got in touch with the headquarters of the Carmelites in the United States, emailing their postulator-general and asking all sorts of questions about related subjects – from preservation and embalming to various interminable mummies around the world, to European and American saints whose bodies are also incorrupt and preserved for public or private viewing, to abstruse theological matters.

Fra. Felip, the Carmelite postulator-general, wrote Berly back;

"Thank you for your interesting message! Regarding the fact of the incorruptibility of your grandmother for 73 years, it could be a miracle, or a natural consequence of other factors, for example, the lack of oxygen necessary for the process of corruption. I have no doubt about the holiness of your grandmother."

"It is the teaching of the Church that you continue to respect and pray for the intercession of your grandmother. But unless there are true signs of a miracle you devotion to her should remain private. God bless you."

Parenthetically, if the friar was correct, there must have been oxygen inside Mama's coffin, that is why the legs decomposed.

But why not the face and head, which must also have been necessarily reached by the oxygen?

In a later message Berly wrote back the friar:

"I have indeed prayed for the intercession of my grandmother privately and I have asked her to help me become a good mother to my two kids ....

"I have appreciated the fact that, instead of material possessions, she left (many) grandchildren – including three priests and three nuns, the legacy of her Catholic faith."

When the clan here in Manila informed Cardinal Sin about the exhumation, he wrote back the next day, saying that Mama's remains "must be entombed again after a pries has blessed them."

Note the cardinal's word, "must."The response of the bishop of Romblon was not exactly the same as that of the Carmelite postulator-general or Cardinal Sin. When informed by Fr. Tony about it, he replied, "She must be a saint!"

That day when they saw Mama's face the first time – May 16, 2001 – Fr. Tony, the devoted parish priest of Guinbirayan in Romblon, somehow felt a prompting to say a Mass for Mama.

He had always prayed for Papa, Mama and other family departed during their special days or anniversaries, but not on May 16 or other days which had no relation to them.

On that day Fr Tony, who was in his parish church in faraway Guinbirayan, did not have the slightest inkling or information about the exhumation being done in Manila.

And yet the urging was so strong and palpable that finally he said the Mass for Mama, with some of his parishioners asking, after he mentioned her name aloud, who Dolores Fainsan y Famadico de Festin was.

Fr. Tony was amazed when Bebet later informed him in Odiongan that Mama's remains were exhumed and found to be incorrupt – on that very same day when something prompted him to say Mass for her.

Mama may have specially chosen Fr. Tony to say the Mass for her because he was the clan's first priest, and is the one taking care of her Colis ancestral house, which Uncle Don had inerited, and the Famadico family's old photographs.

In accordance with Cardinal Sin's wish, Mama's remains were entombed again – in a new tomb built a a level high enough to be, without any doubt this time, free from flooding for the next few decades.

That was done on June 29, 2001 – the first death anniversary of Uncl Toots, and feast day of Peter and Paul.

The coffin containing the remains of Mama, Papa and Uncle Maning were again taken out from their temporary tomb – and opened for the final blessing, as Cardinal Sin had firmly instructed, by Fr. Lorenz, standing on the side of Fr. Tony.

Both Frs. Tony and Lorenz were San Carlos seminarians, the seminary of the cardinal in his capacity as archbishop of Manila.

With the re-exhumation, it was found out, for some inexplicable reason, that this time the coffin was moist, apparently even wet, as some touched it.

And so was everything moist or wet in it – the ribbons, the cloth, even the paper/envelope found on the side of Mama where Papa apparently wrote his last love letter, for all eternity, to Mama.

When one of the cemetery worker, on instruction, tried to pick up what appeared to be the paper/envelope, it proved to have disintegrated into wet dust.

Where did the moisture or wetness come from?

Not from the rains, for they could not have possibly penetrated the old tomb, nor from any flood, because there had not been any since the first exhumation.

Was it because of this overall wet condition that Mama's face, although still smooth and preserved, had to some extent deteriorated?

No matter that her face was not as perfectly preserved as before. For if the purpose was to preserve it so her descendants could see her as she was in life, beautiful and gracious, this had already been achieved in the first exhumation on May 16, and the final, permanent entombment was only in the nature of things.

May 16, by the way, is the birthday of Cori, daughter of Auntie Nitang who named her "Maria Socorro Teresa" the name "Maria" in memory of Mama, who had been baptized "Mariana" more than a century ago.

On the previous year, exactly on May 16, too, Uncle Bert had died.

On the second exhumation that June 29 day, Monique,, with the help of Cori, carefully took hold of Mama's hair to cut off a portion as requested by Berly in a long-distance telephone call from the United States.

And behold, as Monique slowly pulled out Mama's hair, which was perfectly preserved and still firmly attached to her head, it was found to be long and braided.

Monique with scissors respectfully cut off more than a foot long of her braided hair.

In Indiana, Cori cut off a two-inch-long portion of it to be sent to Berly, and the rest is now kept and preserved in Auntie Manti's home.

That night of the same day a big dinner of relatives and friends sponsored by Auntie Manti was held in a nearby restaurant to commemmorate Uncle Toots' death, with a Mass celebrated by Frs. Tony and Lorenz.

There is a footnote to that second exhumation and interment day of June 29.

At about noontime, Cori by phone called Manoling to ask him whether the exhumation would be postponed, owing to the heavy rain.

Because there was a tent above the tombs to keep off any rain, Manoling, who was the one dealing with the cemetery workers, said no, the rain was not much and the final exhumation and interment will go on as scheduled.

But when he was on his way alone in a taxi to the North Cemetery, it rained harder, so very heavily, and the heavens grew very dark that vehicles started to set on their headlights that early afternoon.

Manoling feared the exhumation and re-interment could not go on, after all.

He wondered if he and the other Festins could even get to the cemetery because of the heavy traffic and possible flash flooding of the streets.

Meanwhile, riding in Auntie Manti's car coming from Indiana were Fr. Tony, Sr. Cecille, Cori and Monique, with Andy driving, while Donay also was driving another vehicle, with a video cameral.

The rain – and consequently the traffick – was so heavy they were also thinking aloud, talking to one another, that the afternoon's cemetery actovity may be called off.

In another car coming from Quezon City were Uncle Deric, Auntie Purita, Sr. Emma and Danil, and driver Bert. They, too, wondered about the dark weather and the driving rain.

Luckily the tree cars managed to arrive within minutes of one another just after three o'clock in the afternoon.

Suddenly, not only had the rains stopped, but subdued sunrays appeared, as everybody noticed – the same kind of shafts of light as those of the first exhumation on May 16.

Mama must have strong connections in heaven.

When the remains were being exhumed, blessed and interred, there was not a single drop of rainwater that fell from the sky.

At the same time the cemetery ground was a bit flooded – and stones and slabs had to be arranged by the laborers so that the Festins, to avoid the water, could gingerly step on them in order to approach the tombs.

And as they left the cemetery, the rains fell again like crazy. It took them almost two hours to reach Indiana. Coincidence – or more than that?

## The Famadicos

## The Festins

## The All-Time Champion

## Uncle Bern's Family

## Auntie Nitang's Family

## Uncle Malvs' Family

## Uncle Pol's Family

## Uncle Toots the Treasure Hunter

## Uncle Don and Family

## Auntie Nen and Family

## Uncle Deric and Family

## Uncle Bebs and Family

## Auntie Pans and Family

## Mama Poying

```{r}
1 + 1
```
