# FOREWORD

THIS BOOK is for private purposes only. It is not for public reading or public distribution.

Hence only a handful of copies have been printed – by personal computer – and only a few members of the Festin clan have them.

It is also not intended for release to any member of media or any other institution for their print and broadcast outlets i limited or extended parts.

The present Festins regard this book as their humble tribute to their old and immediate forebears – and their gift to the coming generation of Festins, especially the little children today who are growing up in a vastly different world – vastly different even from that of their fathers and mothers who grew up in rural Philippines.

The first identifiable Festin lived more than 150 years ago. He was captured in his lair in the island province of Romblon by southern raiders and held as a slave until he escaped and sailed back to his little village where, for his exploits, he was acclaimed as the local superstar.

[Result of Internet search on Manuel Festin (aka Lolo Aweng)](https://silaknews.tripod.com/vol3no1/historical.html "Thanks2DeliaFamatigan")

The focus of this book is on Papa and Mama and their eleven children – and their 80 grandchildren, from whose viewpoint it was written.

The generation of these 80 grandchildren – who would have been about 90 or more if the natural abortions or miscarriages are counted – started when Rey, the first child of Uncle Bern and Auntie Mels, was born in 1942, and ended with the birth in 1980 of Andy, the last child of Uncle Toots and Auntie Manti.

Of course, there can be no determination yet of the final count of the great-grandchildren, now about 200, most of whom are still kids and are growing in number and spreading in geographic location, here and abroad, somewhat along the theory of the expanding universe.

This book is the Festin grandchildren's first – and hopefully not their last – collective effort.

I was inspired by Mama whose face and head were found incorrupt when her remains were exhumed this year (2001), 73 years after her death (1928).

```{r}

#| 
```

Only 28 copies, to be exact, are being printed. Each of the ten families will receive one copy.

Auntie Manti will get two extra copies. This is for her most helpful role – and because her residence in Indiana was the venue for meetings and the clearing house for communications in the making of this book.

Renina and Bebet will get one personal copy each because they submitted their written contributions way ahead of the August 22, 2001 deadline.

Renina's work arrived in Manila from Canada as early as August 2 – while Bebet's came from San Andres on August 15.

Three more extra volumes will be given to Auntie Manti in Indiana to be lent to Festins who do not have a copy but wish to read it.

These three copies will be collectively owned by the clan and all borrowers must return every volume borrowed – after two months – to give a chance to other Festins who may want to read it.

Just as Manoling painstakingly printed on his computer thousands upon thousands of pages on bond paper, other Festins could xerox extra copies for their own keeping.

The National Library and the libraries of the University of the Philippines and the Ateneo resort to xeroxing copies of books they loan to their students.

The rest of this book's original volumes will be kept for himself by the one-man publisher, the Festin-crazed Manoling, who worked every day and every night for four months, always going to sleep only after four in the morning and sometimes up to dawn, quaffing beer as assiduously as Minnie's Chinese great-grandfather smoked a kind of drug to keep his energy level high.

For whatever good things this book may have, the credit belongs to the major contributors to its writing.

They are Uncle Don, Uncle Deric, Renina, Manoling, Dulce and Mario, Minnie, Frs. Jujo and Lorenz, Bebet, Cherrie (through an interview), Tony (Solis) and Edmund, with other Festins helping along and raising the clan's spirit with their interest and cooperation.

Because of the haste with which Manoling obsessively produced these volumes, all the many mistakes, omissions, hideous typographical and production flaws, uneven print qualities in both photographs and text, are horrors which he has no choice but to crave as solely his own, and for which he asks for forbearance and patience from those who will be disappointed.

Maybe later, a group of wealthy Festins may publish this book again without its present flaws with the help of a real professional printer.

In the meantime, this volume is coming out for private distribution from Indiana on the last week of September, 2001.

It is possible that in the Philippines at least this is the only book of its kind of format, enthusiastically participated in its making by every family. Long live the Festins.
